const STYLE_ATTRIBUTE = 'dsh-security-assurance/workbench'

const WORKBENCH_CSS = `
.dsh-security-launcher{align-items:center;background:transparent;border:0;border-radius:8px;color:var(--dsw-alias-text-primary,#262626);cursor:pointer;display:flex;font:inherit;gap:10px;min-height:36px;padding:8px 10px;text-align:left;width:100%}
.dsh-security-launcher:hover,.dsh-security-launcher:focus-visible{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.055));outline:none}
.dsh-security-launcher[data-wide=false]{justify-content:center;padding-inline:0}
.dsh-security-launcher__icon{align-items:center;display:inline-flex;flex:0 0 auto;justify-content:center}
.dsh-security-backdrop{align-items:center;background:rgba(9,14,25,.46);display:flex;inset:0;justify-content:center;padding:clamp(12px,3vw,32px);pointer-events:auto;position:absolute}
.dsh-security-dialog{background:var(--dsw-alias-bg-primary,#fff);border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.12));border-radius:18px;box-shadow:0 24px 70px rgba(0,0,0,.24);color:var(--dsw-alias-text-primary,#202124);display:flex;flex-direction:column;max-height:min(760px,calc(100vh - 24px));max-width:920px;min-height:360px;overflow:hidden;width:100%}
.dsh-security-dialog__header{align-items:center;border-bottom:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.1));display:flex;justify-content:space-between;padding:18px 20px}
.dsh-security-dialog__title{font-size:18px;font-weight:650;letter-spacing:-.01em;margin:0}
.dsh-security-dialog__close{align-items:center;background:transparent;border:0;border-radius:8px;color:inherit;cursor:pointer;display:inline-flex;height:34px;justify-content:center;width:34px}
.dsh-security-dialog__close:hover,.dsh-security-dialog__close:focus-visible{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.055));outline:none}
.dsh-security-dialog__body{display:flex;flex:1;min-height:0;overflow:auto;padding:20px}
.dsh-security-empty{align-items:center;border:1px dashed var(--dsw-alias-border-subtle,rgba(0,0,0,.18));border-radius:14px;display:flex;flex:1;flex-direction:column;justify-content:center;min-height:280px;padding:40px;text-align:center}
.dsh-security-empty__icon{align-items:center;background:var(--dsw-alias-bg-hover,rgba(0,0,0,.055));border-radius:50%;display:flex;height:48px;justify-content:center;margin-bottom:16px;width:48px}
.dsh-security-empty h2{font-size:16px;margin:0 0 8px}
.dsh-security-empty p{color:var(--dsw-alias-text-secondary,#666);line-height:1.55;margin:0;max-width:480px}
.dsh-security-message__detail{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.055));border-radius:7px;margin-top:16px;max-width:100%;overflow-wrap:anywhere;padding:7px 9px}
.dsh-security-selection{display:flex;flex:1;flex-direction:column;gap:16px;min-width:0}.dsh-security-selection h2{font-size:16px;margin:0 0 6px}.dsh-security-selection>div>p{color:var(--dsw-alias-text-secondary,#666);font-size:12px;margin:0}.dsh-security-selection__list{display:flex;flex-direction:column;gap:8px;list-style:none;margin:0;padding:0}.dsh-security-selection__list button{align-items:center;background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.1));border-radius:11px;color:inherit;cursor:pointer;display:flex;font:inherit;gap:16px;justify-content:space-between;padding:12px;text-align:left;width:100%}.dsh-security-selection__list button:hover,.dsh-security-selection__list button:focus-visible{border-color:var(--dsw-alias-text-secondary,#666);outline:none}.dsh-security-selection__identity{display:flex;flex-direction:column;gap:5px;min-width:0}.dsh-security-selection__identity code{font-size:12px;overflow-wrap:anywhere}.dsh-security-selection__identity small{color:var(--dsw-alias-text-secondary,#666);font-size:11px;overflow-wrap:anywhere}
.dsh-security-selection__list button:disabled{cursor:wait;opacity:.62}.dsh-security-selection__load-more{align-self:center;background:transparent;border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.16));border-radius:9px;color:inherit;cursor:pointer;font:inherit;padding:8px 14px}.dsh-security-selection__load-more:hover,.dsh-security-selection__load-more:focus-visible{border-color:var(--dsw-alias-text-secondary,#666);outline:none}.dsh-security-selection__load-more:disabled{cursor:wait;opacity:.62}
.dsh-security-view-heading{align-items:center;display:flex;gap:12px;justify-content:space-between}.dsh-security-view-heading h2{margin:0}.dsh-security-view-heading__actions{align-items:center;display:flex;flex-wrap:wrap;gap:8px}.dsh-security-repository-list{display:flex;flex-direction:column;gap:12px;list-style:none;margin:0;padding:0}.dsh-security-repository-list>li{border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.12));border-radius:12px;display:flex;flex-direction:column;gap:12px;padding:13px}.dsh-security-repository-list__heading{align-items:flex-start;display:flex;gap:12px;justify-content:space-between}.dsh-security-repository-list__heading>div{display:flex;flex-direction:column;gap:5px;min-width:0}.dsh-security-repository-list__heading code{font-size:11px;overflow-wrap:anywhere}.dsh-security-repository-list .dsh-security-risk-decision__submit{margin-top:0}
.dsh-security-wizard{display:flex;flex:1;flex-direction:column;gap:16px;min-width:0}.dsh-security-wizard h2{font-size:17px;margin:0 0 8px}.dsh-security-wizard__repository{display:block;font-size:11px;margin-top:5px;overflow-wrap:anywhere}.dsh-security-wizard__form{display:grid;gap:13px;grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-security-wizard__form>.dsh-security-risk-decision__field:has(textarea),.dsh-security-wizard__controls,.dsh-security-wizard__form>.dsh-security-risk-decision__submit{grid-column:1/-1}.dsh-security-risk-decision__field select{background:var(--dsw-alias-bg-primary,#fff);border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.2));border-radius:8px;color:inherit;font:inherit;font-size:12px;padding:9px}.dsh-security-risk-decision__field select:focus-visible{border-color:var(--dsw-alias-text-secondary,#666);outline:none}.dsh-security-wizard__controls{border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.12));border-radius:10px;display:flex;flex-direction:column;gap:8px;margin:0;padding:11px}.dsh-security-wizard__controls legend{font-size:12px;font-weight:650;padding:0 5px}.dsh-security-wizard__controls label{align-items:center;display:grid;font-size:12px;gap:5px 8px;grid-template-columns:auto 1fr}.dsh-security-wizard__controls code{font-size:10px;grid-column:2;overflow-wrap:anywhere}.dsh-security-preflight{border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.12));border-radius:12px;padding:15px}.dsh-security-preflight__limitations{color:var(--dsw-alias-text-secondary,#666);font-size:12px;line-height:1.5;margin:7px 0 0;padding-left:20px}.dsh-security-preflight__digest{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border-radius:9px;display:flex;flex-direction:column;font-size:12px;gap:6px;padding:10px}.dsh-security-preflight__digest code{font-size:10px;overflow-wrap:anywhere}
.dsh-security-health{display:flex;flex:1;flex-direction:column;gap:14px;min-width:0}.dsh-security-health__actions{justify-content:flex-start}.dsh-security-health__admission,.dsh-security-health__checks{display:flex;flex-direction:column;gap:7px;list-style:none;margin:12px 0 0;padding:0}.dsh-security-health__admission li{align-items:center;background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border-radius:8px;display:flex;font-size:12px;justify-content:space-between;padding:9px 10px}.dsh-security-health__checks>li{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border-radius:9px;display:flex;flex-direction:column;gap:7px;padding:10px 11px}.dsh-security-health__check-heading{align-items:center;display:flex;gap:12px;justify-content:space-between}.dsh-security-health__check-heading code{font-size:11px;overflow-wrap:anywhere}.dsh-security-health__checks p{color:var(--dsw-alias-text-secondary,#666);font-size:12px;line-height:1.5;margin:0;overflow-wrap:anywhere}.dsh-security-health__requirement{color:var(--dsw-alias-text-secondary,#666);font-size:11px}
.dsh-security-assessment{display:flex;flex:1;flex-direction:column;gap:16px;min-width:0}
.dsh-security-assessment__heading{align-items:flex-start;display:flex;gap:16px;justify-content:space-between}
.dsh-security-eyebrow{color:var(--dsw-alias-text-secondary,#666);display:block;font-size:12px;font-weight:650;letter-spacing:.06em;margin-bottom:5px;text-transform:uppercase}
.dsh-security-assessment__id{display:block;font-size:14px;overflow-wrap:anywhere}
.dsh-security-badges{display:flex;flex-wrap:wrap;gap:7px;justify-content:flex-end}
.dsh-security-badge{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.06));border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.1));border-radius:999px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:11px;font-weight:700;padding:4px 8px}
.dsh-security-badge[data-value=GAP],.dsh-security-badge[data-value=FAILED],.dsh-security-badge[data-value=FAIL],.dsh-security-badge[data-value=BLOCKED],.dsh-security-badge[data-value=READ_ONLY_SAFE],.dsh-security-badge[data-value=STOPPED],.dsh-security-badge[data-value=false]{background:rgba(196,61,39,.1);border-color:rgba(196,61,39,.25)}
.dsh-security-badge[data-value=SATISFIED],.dsh-security-badge[data-value=COMPLETE],.dsh-security-badge[data-value=SEALED],.dsh-security-badge[data-value=READY],.dsh-security-badge[data-value=PASS],.dsh-security-badge[data-value=true]{background:rgba(31,135,84,.1);border-color:rgba(31,135,84,.25)}
.dsh-security-badge[data-value=QUIESCING],.dsh-security-badge[data-value=NOT_EVALUATED]{background:rgba(190,120,20,.1);border-color:rgba(190,120,20,.3)}
.dsh-security-facts{display:grid;gap:1px;grid-template-columns:repeat(2,minmax(0,1fr));margin:0;overflow:hidden}
.dsh-security-facts>div{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));min-width:0;padding:11px 12px}
.dsh-security-facts dt{color:var(--dsw-alias-text-secondary,#666);font-size:11px;margin-bottom:4px}
.dsh-security-facts dd{font-size:13px;margin:0;overflow-wrap:anywhere}
.dsh-security-facts code{white-space:normal}
.dsh-security-section{border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.1));border-radius:12px;padding:14px}
.dsh-security-section__header{align-items:center;display:flex;gap:12px;justify-content:space-between}
.dsh-security-section h2{font-size:14px;margin:0}
.dsh-security-section__action{margin-top:12px}
.dsh-security-progress,.dsh-security-roles{display:flex;flex-direction:column;gap:12px}.dsh-security-progress__label{font-size:12px}.dsh-security-progress__phases{display:grid;gap:8px;grid-template-columns:repeat(3,minmax(0,1fr));list-style:none;margin:0;padding:0}.dsh-security-progress__phases li{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border-radius:9px;display:flex;flex-direction:column;gap:8px;padding:10px}.dsh-security-progress__phases li>div{align-items:center;display:flex;flex-wrap:wrap;gap:8px;justify-content:space-between}.dsh-security-progress__phases code{font-size:10px;overflow-wrap:anywhere}.dsh-security-progress__phases small{color:var(--dsw-alias-text-secondary,#666);font-size:10px;overflow-wrap:anywhere}.dsh-security-role-cards{display:flex;flex-direction:column;gap:10px}.dsh-security-role-card{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.025));border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.1));border-radius:10px;display:flex;flex-direction:column;gap:12px;padding:12px}.dsh-security-role-card__heading{align-items:flex-start;display:flex;gap:12px;justify-content:space-between}.dsh-security-role-card__heading>div{display:flex;flex-direction:column;gap:5px;min-width:0}.dsh-security-role-card__heading code{font-size:12px;overflow-wrap:anywhere}.dsh-security-role-card__heading small{color:var(--dsw-alias-text-secondary,#666);font-size:9px;overflow-wrap:anywhere}
.dsh-security-role-detail{border-top:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.1));display:flex;flex-direction:column;gap:12px;padding-top:12px}.dsh-security-role-detail__heading{align-items:center;display:flex;gap:10px;justify-content:space-between}.dsh-security-role-detail__heading strong{font-size:12px}.dsh-security-role-detail__published{display:flex;flex-direction:column;gap:12px}.dsh-security-deep-pass{background:rgba(65,105,225,.06);border:1px solid rgba(65,105,225,.2);border-radius:9px;display:flex;flex-direction:column;gap:10px;padding:10px}.dsh-security-deep-pass__phases{display:grid;gap:7px;grid-template-columns:repeat(3,minmax(0,1fr));list-style:none;margin:0;padding:0}.dsh-security-deep-pass__phases li{align-items:center;background:var(--dsw-alias-bg-primary,#fff);border-radius:7px;display:flex;flex-direction:column;font-size:11px;gap:7px;padding:8px;text-align:center}
.dsh-security-metrics{display:grid;gap:10px;grid-template-columns:repeat(2,minmax(0,1fr));margin-top:12px}
.dsh-security-metric{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border-radius:9px;display:flex;flex-direction:column;gap:4px;padding:10px 12px}
.dsh-security-metric span{color:var(--dsw-alias-text-secondary,#666);font-size:11px}.dsh-security-metric strong{font-size:17px}
.dsh-security-readonly-note,.dsh-security-muted{color:var(--dsw-alias-text-secondary,#666);font-size:12px;line-height:1.5;margin:8px 0 0}
.dsh-security-exports{display:flex;flex:1;flex-direction:column;gap:14px;min-width:0}.dsh-security-exports>.dsh-security-secondary-action{align-self:flex-start}.dsh-security-export-list{display:flex;flex-direction:column;gap:7px;list-style:none;margin:12px 0 0;padding:0}.dsh-security-export-list>li{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border-radius:9px;display:flex;flex-direction:column;font-size:11px;gap:6px;padding:10px 11px}.dsh-security-export-list__heading{align-items:center;display:flex;gap:12px;justify-content:space-between}.dsh-security-export-list code{overflow-wrap:anywhere}.dsh-security-export-list small{color:var(--dsw-alias-text-secondary,#666)}.dsh-security-export-list__digest{font-size:10px}.dsh-security-export-list--destinations>li{font-weight:650}
.dsh-security-actions{display:flex;flex-direction:column;gap:8px;list-style:none;margin:12px 0 0;padding:0}
.dsh-security-actions li{align-items:baseline;background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border-radius:9px;display:grid;gap:4px 12px;grid-template-columns:minmax(150px,auto) 1fr auto;padding:10px 12px}
.dsh-security-actions code{font-size:11px;font-weight:700}.dsh-security-actions span{font-size:12px}.dsh-security-actions small{color:var(--dsw-alias-text-secondary,#666);font-size:11px}
.dsh-security-recovery{border-color:rgba(196,61,39,.3);display:flex;flex-direction:column;gap:12px}.dsh-security-recovery__label{font-size:12px}.dsh-security-recovery__form{border-top:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.1));display:flex;flex-direction:column;gap:11px;padding-top:12px}.dsh-security-recovery__actions{align-items:center;display:flex;flex-wrap:wrap;gap:9px}.dsh-security-recovery__cancel{border-color:rgba(196,61,39,.4);color:#a82d1c}
.dsh-security-recovery__no-action{background:rgba(196,61,39,.08);border-left:3px solid rgba(196,61,39,.8);display:flex;flex-direction:column;font-size:12px;gap:5px;line-height:1.5;margin:0;padding:9px 11px}
.dsh-security-primary-action{align-self:flex-start;background:var(--dsw-alias-text-primary,#202124);border:1px solid currentColor;border-radius:9px;color:var(--dsw-alias-bg-primary,#fff);cursor:pointer;font:inherit;font-size:12px;font-weight:650;padding:9px 13px}.dsh-security-primary-action:hover,.dsh-security-primary-action:focus-visible{outline:2px solid var(--dsw-alias-text-secondary,#666);outline-offset:2px}.dsh-security-primary-action:disabled{cursor:wait;opacity:.62}
.dsh-security-secondary-action{background:transparent;border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.16));border-radius:8px;color:inherit;cursor:pointer;font:inherit;font-size:12px;padding:7px 10px}.dsh-security-secondary-action:hover,.dsh-security-secondary-action:focus-visible{border-color:var(--dsw-alias-text-secondary,#666);outline:none}.dsh-security-secondary-action:disabled{cursor:wait;opacity:.62}.dsh-security-finding-list{display:flex;flex-direction:column;gap:8px;list-style:none;margin:12px 0 0;padding:0}.dsh-security-finding-list>li>button{align-items:flex-start;background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.1));border-radius:10px;color:inherit;cursor:pointer;display:flex;font:inherit;gap:12px;justify-content:space-between;padding:11px;text-align:left;width:100%}.dsh-security-finding-list>li>button:hover,.dsh-security-finding-list>li>button:focus-visible{border-color:var(--dsw-alias-text-secondary,#666);outline:none}.dsh-security-finding-list>li>button:disabled{cursor:wait;opacity:.62}.dsh-security-finding-list__identity{display:flex;flex:1;flex-direction:column;gap:5px;min-width:0}.dsh-security-finding-list__identity code{font-size:11px;overflow-wrap:anywhere}.dsh-security-finding-list__identity small{color:var(--dsw-alias-text-secondary,#666);font-size:11px}.dsh-security-finding-list__dimensions{align-items:center;display:flex;flex-wrap:wrap;gap:6px;justify-content:flex-end}.dsh-security-finding-list__dimensions>span:not(.dsh-security-badge){color:var(--dsw-alias-text-secondary,#666);font-size:11px}.dsh-security-finding-detail{display:flex;flex-direction:column;gap:13px}.dsh-security-finding-detail__id{font-size:11px;overflow-wrap:anywhere}.dsh-security-finding-detail__anchor{display:flex;flex-direction:column;gap:5px}.dsh-security-finding-detail__anchor strong,.dsh-security-finding-detail>div>strong{font-size:12px}.dsh-security-finding-detail__anchor code{font-size:11px;overflow-wrap:anywhere}.dsh-security-metadata-list{display:flex;flex-direction:column;gap:6px;list-style:none;margin:8px 0 0;padding:0}.dsh-security-metadata-list li{align-items:center;background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border-radius:8px;display:flex;flex-wrap:wrap;font-size:11px;gap:8px;padding:8px}.dsh-security-metadata-list code{overflow-wrap:anywhere}
.dsh-security-evidence-link{align-items:center;background:transparent;border:0;border-radius:6px;color:inherit;cursor:pointer;display:flex;flex:1;flex-wrap:wrap;font:inherit;font-size:11px;gap:8px;min-width:0;padding:3px;text-align:left}.dsh-security-evidence-link:hover,.dsh-security-evidence-link:focus-visible{outline:2px solid var(--dsw-alias-text-secondary,#666);outline-offset:2px}.dsh-security-evidence-link:disabled{cursor:wait;opacity:.62}.dsh-security-evidence-link code{flex:1;min-width:180px}
.dsh-security-evidence-disclosure-action{align-self:flex-start;background:var(--dsw-alias-text-primary,#202124);border:1px solid currentColor;border-radius:9px;color:var(--dsw-alias-bg-primary,#fff);cursor:pointer;font:inherit;font-size:12px;font-weight:650;padding:9px 12px}.dsh-security-evidence-disclosure-action:hover,.dsh-security-evidence-disclosure-action:focus-visible{outline:2px solid var(--dsw-alias-text-secondary,#666);outline-offset:2px}.dsh-security-evidence-disclosure{display:flex;flex-direction:column;gap:13px}.dsh-security-evidence-sensitivity{align-items:flex-start;background:rgba(196,61,39,.08);border:1px solid rgba(196,61,39,.35);border-radius:9px;display:flex;flex-direction:column;font-size:12px;gap:4px;line-height:1.5;margin:0;padding:10px 12px}.dsh-security-evidence-sensitivity strong{font-size:12px}.dsh-security-evidence-expired{border-left:3px solid var(--dsw-alias-text-secondary,#666);font-size:12px;line-height:1.5;margin:0;padding:8px 10px}.dsh-security-evidence-disclosure__json{background:#111827;border:1px solid rgba(255,255,255,.14);border-radius:10px;color:#f8fafc;font-size:12px;line-height:1.5;margin:0;max-height:320px;max-width:100%;overflow:auto;padding:12px;white-space:pre-wrap;word-break:break-word}.dsh-security-evidence-disclosure__json code{font:inherit}
.dsh-security-risk-decision{border-top:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.1));display:flex;flex-direction:column;gap:12px;padding-top:13px}.dsh-security-risk-decision__form{display:flex;flex-direction:column;gap:12px}.dsh-security-risk-decision__form fieldset{border:0;margin:0;padding:0}.dsh-security-risk-decision__form legend,.dsh-security-risk-decision__field>span{font-size:12px;font-weight:650;margin-bottom:7px}.dsh-security-risk-decision__options{display:grid;gap:8px;grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-security-risk-decision__options label{align-items:center;background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.12));border-radius:9px;cursor:pointer;display:grid;font-size:12px;gap:4px 8px;grid-template-columns:auto 1fr;padding:9px}.dsh-security-risk-decision__options code{font-size:10px;grid-column:2;overflow-wrap:anywhere}.dsh-security-risk-decision__field{display:flex;flex-direction:column}.dsh-security-risk-decision__field textarea,.dsh-security-risk-decision__field input{background:var(--dsw-alias-bg-primary,#fff);border:1px solid var(--dsw-alias-border-subtle,rgba(0,0,0,.2));border-radius:8px;color:inherit;font:inherit;font-size:12px;padding:9px}.dsh-security-risk-decision__field textarea:focus-visible,.dsh-security-risk-decision__field input:focus-visible{border-color:var(--dsw-alias-text-secondary,#666);outline:none}.dsh-security-risk-decision__field textarea[readonly]{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035))}.dsh-security-risk-decision__field small{color:var(--dsw-alias-text-secondary,#666);font-size:10px;margin-top:5px}.dsh-security-risk-decision__consequence,.dsh-security-risk-decision__warning{border-left:3px solid var(--dsw-alias-text-secondary,#666);display:flex;flex-direction:column;font-size:12px;gap:5px;line-height:1.45;margin:0;padding:8px 10px}.dsh-security-risk-decision__warning{background:rgba(196,61,39,.08);border-left-color:rgba(196,61,39,.8)}.dsh-security-risk-decision__submit{align-self:flex-start;background:var(--dsw-alias-text-primary,#202124);border:1px solid currentColor;border-radius:9px;color:var(--dsw-alias-bg-primary,#fff);cursor:pointer;font:inherit;font-size:12px;font-weight:650;padding:9px 13px}.dsh-security-risk-decision__submit:hover,.dsh-security-risk-decision__submit:focus-visible{outline:2px solid var(--dsw-alias-text-secondary,#666);outline-offset:2px}.dsh-security-risk-decision__submit:disabled{cursor:wait;opacity:.62}.dsh-security-risk-decision__attestation{background:var(--dsw-alias-bg-hover,rgba(0,0,0,.035));border-radius:8px;display:grid;font-size:11px;gap:5px;padding:9px}.dsh-security-risk-decision__attestation code{overflow-wrap:anywhere}
@media(max-width:640px){.dsh-security-backdrop{align-items:stretch;padding:0}.dsh-security-dialog{border-radius:0;max-height:none;min-height:100%;width:100%}.dsh-security-dialog__body{padding:14px}.dsh-security-empty{padding:24px}.dsh-security-selection__list button{align-items:flex-start;flex-direction:column}.dsh-security-view-heading{align-items:flex-start;flex-direction:column}.dsh-security-assessment__heading{flex-direction:column}.dsh-security-badges{justify-content:flex-start}.dsh-security-facts{grid-template-columns:1fr}.dsh-security-actions li{grid-template-columns:1fr}.dsh-security-metrics,.dsh-security-risk-decision__options,.dsh-security-wizard__form,.dsh-security-progress__phases,.dsh-security-deep-pass__phases{grid-template-columns:1fr}}
@media(prefers-reduced-motion:no-preference){.dsh-security-backdrop{animation:dsh-security-fade-in .14s ease-out}.dsh-security-dialog{animation:dsh-security-rise-in .18s ease-out}@keyframes dsh-security-fade-in{from{opacity:0}to{opacity:1}}@keyframes dsh-security-rise-in{from{opacity:.7;transform:translateY(8px) scale(.992)}to{opacity:1;transform:none}}}
`

/** Install package-owned CSS for exactly the Client plugin lifetime. */
export function installWorkbenchStyles(): () => void {
  if (typeof document === 'undefined') return () => {}
  const style = document.createElement('style')
  style.dataset.pluginCss = STYLE_ATTRIBUTE
  style.textContent = WORKBENCH_CSS
  document.head.appendChild(style)
  return () => { style.remove() }
}
