import { TYPERT } from 'dsh-security-assurance/typert'
import TYPERT_REMOTE from 'dsh-security-assurance/remote'
import { describe, expect, it } from 'vitest'

interface BoundarySchema {
  parse(value: unknown): unknown
}

interface CompatibleCodec {
  mode: string
  schema: BoundarySchema
  create(): BoundarySchema
}

interface BoundaryInvocation {
  method: string
  parameters: { wire: string; codec: CompatibleCodec }[]
  result: CompatibleCodec
}

// These are the published artifacts, generated by the Harness version under
// test. Every build must be consumable by both supported codec protocols.
for (const [surface, descriptors] of [
  ['Host', (TYPERT as { invocations: BoundaryInvocation[] }).invocations],
  ['Remote client', TYPERT_REMOTE.descriptors],
] as const) {
  const invocations = descriptors as unknown as BoundaryInvocation[]
  describe(`${surface} generated codec compatibility`, () => {
    it('offers the same strict parser through the legacy property and the factory', () => {
      expect(invocations).toHaveLength(19)
      for (const invocation of invocations) {
        for (const codec of [...invocation.parameters.map(parameter => parameter.codec), invocation.result]) {
          expect(codec.mode).toBe('strict')
          expect(codec.create).toBeTypeOf('function')
          expect(codec.create()).toBe(codec.schema)
          expect(codec.create().parse).toBeTypeOf('function')
          expect(() => codec.create().parse(null)).toThrow()
          expect(() => codec.schema.parse(null)).toThrow()
        }
      }
    })

    it('preserves request and result validation across both consumption protocols', () => {
      const cancel = invocations.find(invocation => invocation.method === 'cancelAssessment')!
      const request = cancel.parameters.find(parameter => parameter.wire === 'request')!.codec
      const validRequest = {
        schemaVersion: 1,
        contractVersion: 1,
        assessmentId: 'asm-00000000-0000-4000-8000-000000000001',
        expectedAssessmentRevision: 1,
        reason: { code: 'USER_REQUEST', summary: 'Cancel the assessment.' },
        idempotencyKey: 'codec-compat-cancel',
      }
      const denied = {
        ok: false,
        error: { schemaVersion: 1, code: 'UNAUTHORIZED', message: 'Denied', retryable: false, correlationId: 'codec-compat' },
      }
      for (const schema of [request.schema, request.create()]) {
        expect(schema.parse(validRequest)).toEqual(validRequest)
        expect(() => schema.parse({ ...validRequest, expectedAssessmentRevision: '1' })).toThrow()
      }
      for (const schema of [cancel.result.schema, cancel.result.create()]) {
        expect(schema.parse(denied)).toEqual(denied)
        expect(() => schema.parse({ ok: true, value: {} })).toThrow()
      }
    })
  })
}
